project:
  type: website
  output-dir: docs

website:
  title: "FrederikSpors"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu: 
         - text: "Flights"
           href: Flights_per_Month.qmd
         - text: "Carbon Emission"
           href: CO2_Emission.qmd
         - text: "Netflix Analysis"
           href: Netflix.qmd
         - text: "Permutation Test"
           href: Permutation.qmd
         - text: "Ethics in Data Science"
           href: Ethics.qmd
         - text: "SQL Database"
           href: SQL_Database.qmd
      - href: presentation.html
        text: "Final Presentation"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

