---
title: "Ethical Concerns in the OKCupid Dataset Release"
format:
  html:
    toc: true
    number-sections: true
bibliography: references.bib
citeproc: true
---

**Introduction**

OKCupid is a US-based networking/dating app used for online dating or making new friends with over 30 million users. In 2016, a Danish researcher publicly released data of nearly 70,000 users of the dating site including username, age, gender, location, sexual orientation and other personal information like drug usage. Although this data was sourced from publicly viewable profiles, the release made many people think about the ethical boundaries of using “public” data without consent. The researcher argued that the dataset was released without users’ knowledge that this information will be used for an academic purpose. However, what does “public” really mean? @xiao2021 highlight the core issue and say: "The fact that data is publicly accessible does not mean its reuse is ethically justified." This raises even more questions. Who gets to decide how and what data is reused and should a researcher be allowed to just source personal information from individuals without their given consent? How does this research benefit us or is it more harmful for the individuals?

**Method of Data Collection**

The data was collected through web scraping of publicly available profiles on OkCupid, including self-reported information such as usernames, age, gender, sexual orientation, and personal questions, such as drug usage. Users may have answered some questions inaccurately, as some individuals might lie to present themselves more favorably on a dating site. @xiao2021 argued: "People often answer these questions in ways they think will help them attract partners, not necessarily in ways that reflect their true beliefs or behaviors." Additionally, some individuals might have left some questions blank, making the dataset incomplete.

**Users Consent for using their Data**

The users whose data was used never gave informed consent that their dating profile data would be used for an academic research purpose. Therefore, the researchers used personal data from several thousands of people including their name, sexual identity and other personal information. Users signed up to find potential romantic matches or find new friends, but not for it to be used for an academic purpose. Although the data was always publicly available for everyone to see, @xiao2021 argue that "public" does not mean "fair game." Users didn’t explicitly give consent to their data being used for research purposes and therefore just taking their information isn’t a "fair game." @resnick2016 also reported on this issue and adds: “The data dump breaks the cardinal rule of social science research ethics: It took identifiable personal data without permission." Consent has always been a highly debated topic worldwide and nowadays informed consent is a standard requirement for both clinical and research settings. This is backed by several frameworks including national laws and institutional review boards like the "American Psychological Association" @apa2017ethics which emphasize that participants in studies have the right to informed consent, including knowledge of how their data will be used and have the right to withdraw from research. In this case, the users weren’t informed and didn’t have the opportunity to give consent or opt out as they didn't even know about the study, violating these ethical standards.

**Use of Data in Unintended Ways**

Originally, users gave their personal information to OkCupid for the purpose of finding romantic partners or new friends but not for academic research. @xiao2021 point out that "even if the intention of using this data is pedagogical, ethical issues remain." The researcher wanted to conduct social science research and the release should’ve contributed to the so called "open data" movement for students to have real-word datasets to analyze. Therefore, the data was sourced without any malicious intent. However, as @resnick2016 notes, “The profiles might technically be public, but why would OkCupid users expect anyone else but other users to look at them?” This is a very valid question to ask yourself because you wouldn’t expect that signing up for a dating site will lead to you being featured in an academic research dataset and is thus not ethically correct as they weren't informed about that.

**Harms to Vulnerable People**

@xiao2021 mention that “There are risks of harm, especially for vulnerable individuals whose identities or private lives may be exposed.” This risk can especially impact marginalised groups, such as LGBTQ+ users or individuals sharing about their drug usage. These are very sensitive topics and users were open to sharing this information within the dating platform as the audience was limited to other users with similar intentions, but not the wider public for research. The research included their usernames and location, making it possible to track back their real-world identities and creating real-world consequences such as outing or professional repercussions. The users also didn’t know that they would be part of that dataset and didn’t even have the chance to back out.

**Conclusion**

As seen from this example, data that is made available publicly does not automatically justify its ethical use for research. Although the researchers wanted to collect the data on OkCupid users for an educational purpose, the users whose data was used did not give informed consent. Sourcing this data can potentially harm vulnerable individuals and make this case even more problematic as they don’t want to be publicly exposed. As @xiao2021 pointed out, even pedagogical uses of data does not justify important research principles like consent or privacy. Just because data is available it doesn’t mean it should be collected and analyzed. Therefore, researchers always have to be aware of the rights of the individuals represented in the data and whether they actually consented to take part in the research.
